### ISSUE TITLE
getting this working with minikube

### ISSUE THREAD

**Issue by Analect** [data-8/jupyterhub-k8s#32]
Hi. Thanks for this project ... realise it's WIP ... but can I ask a quick question ref. getting this working against minikube.  Instead of references to gcloud storage in the README, is it possible to run this up locally, for testing using [these settings](https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard), which appear to allow you to specify a local directory for storage.

I adjusted the manifest.yaml files as follows, commenting out the gcePersistentDisk part:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data8-hub-workdir-01
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mypath/kubernetes/data"
#  gcePersistentDisk:
#    pdName: data8-hub-workdir-01
#    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data8-workdir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

If I then run:
`kubectl apply -f manifest.yaml`
I get this response, but it doesn't appear to launch anything, eventhough I have the hub and cull images available locally?

```
configmap "cull-config" configured
persistentvolume "data8-hub-workdir-01" configured
persistentvolumeclaim "data8-workdir" configured
service "hub-proxy" configured
deployment "hub-proxy-deployment" configured
deployment "cull-deployment" configured
```

Am I missing something ... or is this just not possible using minikube?  Thanks.
